solumon-front/style/theme.js

`  dark_purple: '#292435',
medium_purple: '#5C5470',
light_purple: '#B9B4C7',
linen: '#FAF0E6',`

Design: (chaeeun/develop/#4) styled-components 사용을 위한 theme 생성

---

solumon-front/src/components/TabsComponent.jsx

Feat:(eunsoo-cho/feature/component/#3) 탭바 구현

:sparkles: [Feature/component/#3] 탭바 구현

---

solumon-front/package-lock.json
solumon-front/package.json
solumon-front/public/mockServiceWorker.js
solumon-front/src/components/NavigationBar.jsx
solumon-front/src/components/Pagination.jsx
solumon-front/src/components/SortSelector.jsx
solumon-front/src/components/UserMenu.jsx

은수님한테 파일 단위로 pr 보내자고 해놓고 저는 왜 그랬을까요..?
push를 취소하는 방법을 찾아봤는데 여러모로 어려울 것 같아서 일단은 pr 보냅니다.
그래도 다행인건 여기 커밋해둔 컴포넌트들이 아직 제대로 구현된게 아니라서 제대로 수정하고 나면 
그때부터는 반드시 파일 하나만 push하고 pr 보내도록 하겠습니다...(;´༎ຶД༎ຶ`)

[Feature/component/#3] 그동안의 밀린 커밋들

---

solumon-front/package-lock.json
solumon-front/package.json
solumon-front/public/mockServiceWorker.js
solumon-front/src/components/NavigationBar.jsx
solumon-front/src/components/Pagination.jsx
solumon-front/src/components/PostCard.jsx
solumon-front/src/components/SortSelector.jsx
solumon-front/src/components/UserMenu.jsx

게시글 카드 컴포넌트 구현 했고,
msw 적용시킨 코드 push 후 merge 하면 될 것 같아요!

:sparkles:[feature/component/#3] 게시글 카드 컴포넌트 구현

---

solumon-front/src/components/PostInputForm.jsx
solumon-front/src/components/TabsComponent.jsx
solumon-front/src/components/TextButton.jsx
solumon-front/src/mocks/browser.js
solumon-front/src/mocks/handlers.js

:white_check_mark:Test (chaeeun/feature/component/#3) PostCard에 해당하는 API 추가

---

solumon-front/src/App.jsx
solumon-front/src/pages/sign-up/SignUpGeneral.jsx
solumon-front/src/pages/sign-up/SignUpKakao.jsx

이메일 회원가입 페이지 url: /sign-up/general
카카오 회원가입 페이지 url: /sign-up/kakao

✨[Feature/component/#15] 회원가입 페이지 UI 구현 & 라우팅

---

.vscode/settings.json
solumon-front/.prettierrc.json
solumon-front/package-lock.json
solumon-front/package.json

eslint, prettier 설치 후 필요한 파일들 설정 했습니다.

:wrench:[develop] eslint, prettier 파일 설치 및 설정

---

solumon-front/package-lock.json
solumon-front/package.json
solumon-front/src/main.jsx
solumon-front/src/mocks/browser.js
solumon-front/src/mocks/handlers.js
solumon-front/src/pages/sign-up/SignUpGeneral.jsx

Axios 설치 후 이메일 회원가입 페이지에 필요한 테스트 API /users 작성했고
Axios 사용해서 fetch 완료

:white_check_mark: [Feature/component/#15] Axios 설치, 이메일 회원가입 페이지 테스트 API 작성

---

solumon-front/package-lock.json
solumon-front/package.json
solumon-front/src/components/Button.jsx

💄 [Feature/component/#3]버튼컴포넌트 수정

---

solumon-front/src/App.jsx
solumon-front/src/components/PostCard.jsx
solumon-front/src/mocks/handlers.js
solumon-front/src/pages/PostList.jsx

페이지 라우팅 ('/post-list') 후 handlers.js 파일에서 데이터를 필요한 형태로 수정했고,
PostCard 컴포넌트에서 props로 받아온 개수만큼 PostCard 렌더링 하는 걸로 코드 수정했습니다.

✨[Feature/component/#15] 전체 게시판 리스트 페이지 구현

---

solumon-front/package-lock.json
solumon-front/package.json
solumon-front/src/pages/Start.jsx

:sparkles: [Feature/componenet/#15] 홈페이지 소개 페이지 구현

---

solumon-front/src/App.jsx
solumon-front/src/components/InterestTopic.jsx
solumon-front/src/mocks/handlers.js
solumon-front/src/pages/ChoiceInterest.jsx
solumon-front/src/recoil/AllAtom.js

- 관심주제 요청 API '/user/interests' 로 페이지 라우팅 및 handler에 코드 추가
- 사용자가 선택한 관심주제 값을 저장하는 UserInterestTopic atom 생성
- 선택한 관심주제 값을 UserInterestTopic에 저장하는 InterestTopic 컴포넌트 구현
- InterestTopic 컴포넌트를 불러와 관심주제를 선택하는 ChoiceInterest 페이지 구현

:sparkles: [Feature/component/#15] 관심주제 선택 페이지 구현

---

solumon-front/src/App.jsx
solumon-front/src/mocks/browser.js
solumon-front/src/mocks/handlers.js
solumon-front/src/pages/Posts.jsx

:sparkles: [Feature/component/#15]게시물작성페이지 구현

---

solumon-front/src/pages/Ban.jsx

:sparkles: [Feature/component/#15] 신고페이지 구현

---

solumon-front/src/components/EditMode.jsx
solumon-front/src/components/HeaderContent.jsx
solumon-front/src/components/VoteResult.jsx
solumon-front/src/components/Votes.jsx
solumon-front/src/pages/PostDetail.jsx

<게시물상세페이지구현>
(닉네임일치유무)
-게시물상세페이지(나의게시물)=>put, delete(수정,삭제)
-게시물상세페이지(상대방게시물)=>투표항목선택(post)

:sparkles: [Feature/component/#15] 게시물상세페이지 구현

---

solumon-front/src/pages/PostCategory.jsx

현재 라우팅 중복되는 문제 있음
sortTab 제외하고 구현

:sparkles [feature/component/#15] 카테고리별 상세 게시글을 보여주는 PostCategory 페이지 구현

---

solumon-front/src/App.jsx
solumon-front/src/components/Button.jsx

버튼 컴포넌트 오류로 인한 코드 수정 및 pull 받기위해 app.js 수정한 것 부득이하게 같이 올립니다...

💄[Feature/component/#3] 버튼 컴포넌트 오류 수정 및 pull받기 위한 파일업로드

---

solumon-front/src/main.jsx
solumon-front/src/pages/FindPassword.jsx
solumon-front/src/pages/Login.jsx
solumon-front/src/pages/UserInfo.jsx
solumon-front/src/pages/WithDraw.jsx
solumon-front/src/pages/sign-up/SignUpGeneral.jsx
solumon-front/src/pages/sign-up/SignUpKakao.jsx

로그인, 일반 회원가입, 카카오 회원가입, 비밀번호 찾기, 회원정보 조회, 회원 탈퇴 페이지
- input 태그 너비 전부 330px로 변경
- 타이틀 font-weight 전부 600 으로 통일
- 비밀번호 입력 & 변경 시 주의 사항을 명시하는 <InfoText> 태그 추가
- <InfoText> 는 주의 사항임을 인식하도록 📢 이모티콘 추가

💄 [Feature/component/#15] 공통 스타일 수정 & 안내 문구 추가

---

solumon-front/src/pages/PostList.jsx

- /posts? 실제 API 연동
- 쿼리 값 대문자로 수정
- loading state 삭제
- PostCard 컴포넌트에 전달할 props 값 추가(postOrder)

✨[feature/component/#46] 게시글 목록 실제 API 연동 

---

solumon-front/src/components/HeaderContent.jsx
solumon-front/src/components/VoteResult.jsx
solumon-front/src/components/Votes.jsx
solumon-front/src/pages/PostDetail.jsx

<PostDetail>
- 내 게시물일때, 기존 닉네임값 비교 방식에서 -> recoil에 저장된 memberId와 게시물 writer_member_id 값비교로 방식으로 변경 
- 기존 코드에서 솔루몬 API 연동하여 코드수정
- handleChoiceClick 클릭 후 vote컴포넌트가 -> voteResult 컴포넌트로 재렌더링될수 있도록 비동기함수 해제

:art: [Feature/component/#46] 게시물 상세페이지 관련 API연동 및 수정

---

solumon-front/src/pages/Ban.jsx

<ban>
-신고페이지 실제 API 연동 
-신고페이지 기존코드에서 ->reported_member_id 값 추가하여 body 에 전달 형태로 변경
-닉네임값을 전달하는 것에서 -> 멤버아이디로 전달 방식으로 변경 (닉네임 변경이 가능하기때문에)

:art: [Feature/component/#46] 신고페이지 API연동 및 코드수정

---

solumon-front/src/pages/Posts.jsx

-게시물 작성 코드 스타일변경
-불필요한 console.log 값 삭제

:lipstick: [Feature/component/#15] 게시물작성페이지 코드 수정

---

solumon-front/src/components/InterestTopic.jsx
solumon-front/src/pages/ChoiceInterest.jsx

>Component
InterestTopic.jsx
- 관심주제 목록 수정
- 선택한 관심주제를 저장하는 Atom 변경 
-> 관심주제만을 저장하는 UserInterestTopic 에서 유저 정보를 저장하는 GeneralUserInfo 에 함께 저장
>Page
ChoiceInterest.jsx
- 선택한 관심주제를 서버에 post 하도록 실제 API 연동

✨🩹 [Feature/component/#46] 관심주제 페이지 수정

---

solumon-front/src/pages/Edit.jsx

-수정페이지 API연동
**(추후 수정해야할 부분)**
**현재코드에서 수정한 사진 파일 저장하는 부분에서 이전에 넘어왔던 파일이 제대로 넘겨지지 않는 오류가 발생.
백엔드응답코드에서 이미지URL 데이터 뿐만아니라 이미지 파일네임까지 요청하여 form 데이터에 파일이름 추가하여 저장 할예정.
->백엔드에서 보내주는 url에서 파일이름을 추출하여 파일 객체로 보내봤지만 제대로된 응답값이 오지않음.

:construction: 🎨  [Feature/component/#46] 수정페이지 API 연동 및 코드 수정

---

solumon-front/src/components/NavigationBar.jsx

- 로그아웃 모달 추가 & 실제 로그아웃 API 연동
- 로컬 스토리지에 저장된 유저 닉네임 불러오도록 코드 수정
- 유저 메뉴 클릭 시 해당 페이지로 이동하도록 Link 태그 추가

✨🚧 [feature/component/#46] 네비게이션 바 코드 수정

---

solumon-front/src/App.jsx

pull받고 오류난 부분 충돌해결후 라우팅 추가 (신고, 수정페이지)

:white_check_mark: [Feature/component/#15] app.js 라우팅 추가(신고,수정페이지)

---

solumon-front/src/pages/FindPassword.jsx
solumon-front/src/pages/MyHistory.jsx
solumon-front/src/pages/UserInfo.jsx
solumon-front/src/pages/WithDraw.jsx

> UserInfo.jsx - 회원정보 조회 & 수정 페이지 
- 회원정보 조회하는 API 연동
- 회원정보 수정하는 API 연동
- 저장된 관심주제 값 불러오는 Atom UserInterestTopic -> GeneralUserInfo 로 수정
- 닉네임을 입력하는 input 태그 value 속성을 defaultValue 로 변경하여 처음엔 설정되어 있던 닉네임을 기본값으로 보여주고 그 값을 수정할 수 있게 함
> MyHistory.jsx - 내가 남긴 기록 페이지
- 페이지 UI 구현
- 내가 작성한 글들을 조회하는 API 연동
> FindPassword.jsx - 비밀번호 찾기 페이지
- 입력한 이메일로 임시 비밀번호를 발급받는 API 연동
> WithDraw.jsx - 회원탈퇴 페이지
- 비밀번호를 입력하면 그에 해당하는 회원을 탈퇴시키는 API 연동

✨[Feature/component/#15/#46] 유저 메뉴들 API 연동

---

solumon-front/src/components/Chat.jsx
solumon-front/src/pages/PostDetail.jsx

[Feature/component/#3] 실시간채팅 컴포넌트 구현 및  api연동
- 웹소켓 , stomp 사용하여 실시간 채팅 구현
- 스크롤 위로 올렸을 때, lastChatMessageId 값을 헤더에 전달해주면서, 이전 채팅 데이터 불러오는 fetchData 구현

:sparkles: [Feature/component/#3] 실시간채팅 컴포넌트 구현

---

solumon-front/src/pages/ChoiceInterest.jsx
solumon-front/src/pages/UserInfo.jsx

> UserInfo.jsx
- 사용자 정보를 firestore에서 불러오는 방식으로 변경
- 사용자 정보를 수정하면 firestore의 db가 업데이트 되도록 구현
- firebase를 사용하여 비밀번호 변경하는 함수 구현
> ChoiceInterest.jsx
- 관심주제 변경 시 firestore의 해당 db가 업데이트 되도록 구현

👽️✨[Feature/component/#15] 회원정보 페이지에 firebase & firestore 적용

---

solumon-front/src/pages/PostCategory.jsx

- 사용하지 않는 TabsComponent 삭제 -> Badge 컴포넌트를 사용하여 투표 기간 종료 여부를 나타냄
- 원하는 순서로 정렬된 게시글을 가져오는 fetchOrderedData 함수 구현

💄 ✨ [Feature/component/#15] PostCategory 페이지 UI 업데이트 & 함수 구현

---

solumon-front/src/components/HashTagList.jsx
solumon-front/src/recoil/AllAtom.js

관심주제 관련 게시글 필터링을 위해 게시글 작성 시 자율적으로 해시태그를 생성하는 방식에서 정해진 해시태그들을 선택할 수 있도록 변경했고 그에 따른 컴포넌트와 recoil atom 생성

✨[Feature/component/#3] 해시태그를 선택할 수 있는 컴포넌트 생성

---

solumon-front/src/pages/sign-up/SignUpGeneral.jsx

-firebase 사용해서 사용자 uid와 닉네임을  'users' 컬렉션에 파이어스토어에 저장하여 일반회원가입 구현

✨ [Feature/component/#15] Firebase 사용하여 SignupGeneral 페이지 수정 

---

solumon-front/src/pages/PostCategory.jsx
solumon-front/src/pages/PostList.jsx

> PostList.jsx - 게시글 리스트 페이지
- 일반 게시글 불러오는 함수 구현
- 관심주제와 관련된 게시글을 필터링해서 불러오는 함수 구현
- 카테고리별 게시글 불러오는 방식 변경
> PostCategory - 카테고리별 전체 게시판 페이지 
- 관심주제와 관련된 게시글을 필터링해서 불러오는 함수 구현
- 관심주제 관련 게시글들을 원하는 순서대로 정렬하도록 코드 추가

✨ [Feature/component/#15] 게시글 관련 페이지들 firebase 적용

---

solumon-front/src/components/HeaderContent.jsx
solumon-front/src/pages/PostDetail.jsx

(postDetail 페이지)
- **fetchData 함수**: 글쓰기 페이지에서 저장했던 post-write 컬렉션의 정보를 가져와서 투표마감시간과 현재시간 비교해서 
setPostStatus 값 저장( vote, voteResult 구분하여 렌더링하기 위해) 
- **checkVoteJoin 함수**: 투표를 했는지 유무 판단하여 votes,voteResult 둘 중의 컴포넌트 렌더링 하기위해 join 값 저장.
- **handleVoteUpdate함수**: 투표 시 해당 투표항목 choice_count와 총 투표 수 업데이트 함수
- **updateVoteJoin함수**: 투표 시 해당유저 users 컬렉션에 해당 게시물 postId 저장하여 중복투표 방지 및 투표 유무 확인.
(headerContent 컴포넌트)
- 파이어베이스 사용한 게시물 삭제 기능 구현

:sparkles: [Feature/component/#15] Firebase) PostDetail 페이지 코드 수정

---

solumon-front/src/components/CommentForm.jsx
solumon-front/src/components/CommentList.jsx

(commentForm 컴포넌트)
- 댓글을 입력하는 댓글 창 컴포넌트 코드작성 (Firebase 사용하여 댓글 작성 시 users컬렉션에 postId 저장)
- Firebase 사용하여 post-write 컬렉션에 댓글 저장
(commentList 컴포넌트)
- commentForm을 통하여 작성한 댓글을 볼 수 있는 댓글 컴포넌트 (로그인유저가 남긴 댓글일 때 수정, 삭제 버튼 구현) 
- 댓글 수정 모드 구현, 수정한 내용 저장하는 기능 구현
- 해당 댓글에 답글 기능 구현

:sparkles: [Feature/component/#3] Firebase) commentForm 댓글 창 컴포넌트 코드 작성

---

solumon-front/src/pages/Edit.jsx

(Edit 페이지)
- Firebase 사용하여 수정모드 변환( 사진 이미지 변환, 제목 글 태그 수정 가능)

:sparkles: [Feature/component/#15] Firebase) Edit 페이지 코드 수정

---

solumon-front/src/pages/Ban.jsx

(Ban  페이지) 
- 부적절한 사용자 파이어베이스 사용하여 report 컬렉션에 신고타입, 멤버아이디, 신고내용 등을 저장하여 관리함.

:sparkles: [Feature/component/#15] Firebase) Ban 페이지 코드 수정

---

solumon-front/src/hooks/useFetchInterestsData.js
solumon-front/src/hooks/useFetchOrderedData.js
solumon-front/src/pages/PostList.jsx

> useFetchInterestsData.js
- 전체 게시글 중 사용자의 관심주제와 관련된 게시글을 가져오는 custom hook 생성
<br />
> useFetchOrderedData.js
- 전체 게시글을 가져오는 custom hook 생성
<br />
> PostList.jsx
- custom hook 을 사용하여 데이터를 가져오도록 수정
- 아직 해결하지 못한 고민들 -> 최근 올라온 고민들로 카테고리 타이틀 변경

:sparkles: [Feature/component/#15] 게시글 데이터를 가져오는 custom hook 생성 & 적용

---

solumon-front/src/components/HeaderContent.jsx
solumon-front/src/components/PostCard.jsx

> PostCard.jsx
반응형 디자인을 위해 페이지 전체 너비를 px 단위에서 vw 단위로 수정
<br />
> HeaderContent.jsx
뒤로가기 버튼 통일을 위한 아이콘 수정

💄 [Develop] UI 수정

---

solumon-front/src/components/CommentForm.jsx
solumon-front/src/components/CommentList.jsx
solumon-front/src/components/HeaderContent.jsx
solumon-front/src/pages/PostDetail.jsx
solumon-front/src/pages/Start.jsx

> 게시글 상세보기 페이지 UI 수정 PostDetail.jsx
- HeaderContent 컴포넌트
- Votes 컴포넌트
- CommentForm 컴포넌트
- CommentList 컴포넌트

💄 [Develop] 게시글 상세보기 페이지 UI 수정

---

solumon-front/src/components/CommentForm.jsx
solumon-front/src/components/CommentList.jsx
solumon-front/src/components/HeaderContent.jsx
solumon-front/src/components/Modal.jsx
solumon-front/src/components/NavigationBar.jsx
solumon-front/src/components/NoData.jsx
solumon-front/src/components/Pagination.jsx
solumon-front/src/components/PostCard.jsx
solumon-front/src/components/SearchBar.jsx
solumon-front/src/components/VoteResult.jsx
solumon-front/src/components/Votes.jsx
solumon-front/src/media.js
solumon-front/src/pages/Login.jsx
solumon-front/src/pages/MyHistory.jsx
solumon-front/src/pages/PostCategory.jsx
solumon-front/src/pages/PostDetail.jsx
solumon-front/src/pages/PostList.jsx
solumon-front/src/pages/Posts.jsx
solumon-front/src/pages/SearchResult.jsx
solumon-front/vercel.json

🐛 [Develop] 피드백 받은 부분 수정 & 수정하며 발견한 문제들 해결
